### PR TITLE
Add createDirectory & uploadFile

### PR DESCRIPTION
**Pull request by gnuletik**
Adding `createDirectory` and `uploadFile`

Sorry for the removing of the `;` at the end of the line. This is how my editor is configured and in the end, it's more clean :)

### CODE REVIEW

**Comment by gnuletik** [comment]
Hi @freeplant ! Any news on this ? Should I fix the conflicts ?

**Comment by freeplant** [comment]
we use 2 spaces for indentation. Please also add back ';'

**Comment by gnuletik** [comment]
@freeplant Done :)

**Comment by freeplant** [comment]
Thanks.

**Pull request merged**
